shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - tinyexec@1.2.2
  - 'semver@6.3.1 || 5.7.2'
  - '@trickfilm400/rollup-plugin-off-main-thread@3.0.0-pre1'

overrides:
  source-map: ^0.7.6

peerDependencyRules:
  allowedVersions:
    vite: ^8.0.14

allowBuilds:
  core-js: true
  esbuild: true
  simple-git-hooks: true
