/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Adjustment': RouteRecordInfo<
      'Adjustment',
      '/adjustment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PendingImage': RouteRecordInfo<
      'PendingImage',
      '/pending-image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Statistics': RouteRecordInfo<
      'Statistics',
      '/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Vehicle': RouteRecordInfo<
      'Vehicle',
      '/vehicle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'VehicleEdit': RouteRecordInfo<
      'VehicleEdit',
      '/vehicle/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WorkOrder': RouteRecordInfo<
      'WorkOrder',
      '/work-order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WorkOrderCreate': RouteRecordInfo<
      'WorkOrderCreate',
      '/work-order/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WorkOrderDetail': RouteRecordInfo<
      'WorkOrderDetail',
      '/work-order/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/work-order/vehicle-history': RouteRecordInfo<
      '/work-order/vehicle-history',
      '/work-order/vehicle-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/adjustment/index.vue': {
      routes:
        | 'Adjustment'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pending-image/index.vue': {
      routes:
        | 'PendingImage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/statistics/index.vue': {
      routes:
        | 'Statistics'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicle/index.vue': {
      routes:
        | 'Vehicle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicle/edit.vue': {
      routes:
        | 'VehicleEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/work-order/index.vue': {
      routes:
        | 'WorkOrder'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/work-order/create.vue': {
      routes:
        | 'WorkOrderCreate'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/work-order/detail.vue': {
      routes:
        | 'WorkOrderDetail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/work-order/vehicle-history.vue': {
      routes:
        | '/work-order/vehicle-history'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
