/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "access-key": () => import("@/views/access-key/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  paint_category: () => import("@/views/paint/category/index.vue"),
  paint_shop: () => import("@/views/paint/shop/index.vue"),
  "paint_standard-template": () => import("@/views/paint/standard-template/index.vue"),
  paint_statistics: () => import("@/views/paint/statistics/index.vue"),
  "paint_work-order": () => import("@/views/paint/work-order/index.vue"),
};
