/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'access-key',
    path: '/access-key',
    component: 'layout.base$view.access-key',
    meta: {
      title: 'access-key',
      i18nKey: 'route.access-key'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'paint',
    path: '/paint',
    component: 'layout.base',
    meta: {
      title: 'paint',
      i18nKey: 'route.paint'
    },
    children: [
      {
        name: 'paint_category',
        path: '/paint/category',
        component: 'view.paint_category',
        meta: {
          title: 'paint_category',
          i18nKey: 'route.paint_category'
        }
      },
      {
        name: 'paint_scheduled-task',
        path: '/paint/scheduled-task',
        component: 'view.paint_scheduled-task',
        meta: {
          title: 'paint_scheduled-task',
          i18nKey: 'route.paint_scheduled-task'
        }
      },
      {
        name: 'paint_shop',
        path: '/paint/shop',
        component: 'view.paint_shop',
        meta: {
          title: 'paint_shop',
          i18nKey: 'route.paint_shop'
        }
      },
      {
        name: 'paint_standard-template',
        path: '/paint/standard-template',
        component: 'view.paint_standard-template',
        meta: {
          title: 'paint_standard-template',
          i18nKey: 'route.paint_standard-template'
        }
      },
      {
        name: 'paint_statistics',
        path: '/paint/statistics',
        component: 'view.paint_statistics',
        meta: {
          title: 'paint_statistics',
          i18nKey: 'route.paint_statistics'
        }
      },
      {
        name: 'paint_work-order',
        path: '/paint/work-order',
        component: 'view.paint_work-order',
        meta: {
          title: 'paint_work-order',
          i18nKey: 'route.paint_work-order'
        }
      }
    ]
  }
];
